export const GET_PRODUCTSBYMARK_REQUEST = "GET_PRODUCTSBYMARK_REQUEST";
export const GET_PRODUCTSBYMARK_SUCCESS = "GET_PRODUCTSBYMARK_SUCCESS";
export const GET_PRODUCTSBYMARK_FAIL = "GET_PRODUCTSBYMARK_FAIL";

export const GET_PRODUCTBYMARK_DETAILS_REQUEST = "GET_PRODUCTBYMARK_DETAILS_REQUEST";
export const GET_PRODUCTBYMARK_DETAILS_SUCCESS = "GET_PRODUCTBYMARK_DETAILS_SUCCESS";
export const GET_PRODUCTBYMARK_DETAILS_FAIL = "GET_PRODUCTBYMARK_DETAILS_FAIL";
export const GET_PRODUCTBYMARK_DETAILS_RESET = "GET_PRODUCTBYMARK_DETAILS_RESET";
